name = "htn252"
compatibility_date = "2024-10-02"
pages_build_output_dir = ".vercel/output/static"
pages_functions_directory = "functions"

[build]
command = "npm run build --workspace master-landing"
