# .github/workflows/deploy-cloudrun.yml
name: Deploy to Cloud Run
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'   # for Workload Identity Federation (no JSON key)
    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDP }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - uses: google-github-actions/setup-gcloud@v2

      - id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: relief-app
          region: us-central1
          source: src           # <— deploy from source (Buildpacks)
          allow-unauthenticated: true
