name: Premerge Tests

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main
      - work

jobs:
  backend-tests:
    name: Pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest

      - name: Run pytest
        run: pytest -q

  frontend-tests:
    name: Vitest (${{ matrix.app }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [ 'donor-dashboard', 'landing' ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          # Cache on lockfile if present; fall back to package.json
          cache-dependency-path: |
            ${{ matrix.app }}/package-lock.json
            ${{ matrix.app }}/package.json

      - name: Install dependencies
        working-directory: ${{ matrix.app }}
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Run unit tests
        working-directory: ${{ matrix.app }}
        run: npm test -- --run
